version: "3.3"

services:

#  mongo:
#    container_name: mongo
#    image: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    volumes:
#      - app-data:/var/lib/mongo/data
#
#  spring:
#    container_name: spring
#    image: maven
#    ports:
#      - "8080:8080"
#    volumes:
#      - './backend/spring:/usr/src/spring'
#      - 'maven-repo:/root/.m2'
#    working_dir: '/usr/src/spring'
#    command: mvn spring-boot:run
    
  react:
    container_name: react
    image: node
    ports:
      - "3000:3000"
    volumes:
      - './frontend/react:/usr/src/react'
    working_dir: '/usr/src/react'
    command: bash -c "npm install && npm start"

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: expensetracker
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  django:
    container_name: django
    depends_on:
      - mysql
    image: django
    ports:
      - "8080:8080"
    volumes:
      - './backend/django/expensetracker:/usr/src/django/expensetracker'
    working_dir: '/usr/src/django/expensetracker'
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py initadmin && python3 manage.py runserver 0.0.0.0:8080"

volumes:
#  app-data:
  mysql-data:
  maven-repo: