version: "3.3"

services:

  spring:
    depends_on:
      - mysql
    container_name: spring
    image: maven
    ports:
      - "8080:8080"
    volumes:
      - './backend/spring:/usr/src/spring'
      - 'maven-repo:/root/.m2'
    working_dir: '/usr/src/spring'
    command: mvn spring-boot:run -Dspring-boot.run.profiles=dev

  react:
    container_name: react
    image: node
    ports:
      - "3000:3000"
    volumes:
      - './frontend/react:/usr/src/react'
    working_dir: '/usr/src/react'
    command: bash -c "npm install && npm run start-dev"
    
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: expensetracker2
      MYSQL_ROOT_PASSWORD: root
    ports:
     - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  maven-repo:
