version: "3.3"

services:

  spring:
   depends_on:
    - mysql
   container_name: spring
   image: acrackintheice/expense-tracker-spring
   ports:
     - "8080:8080"
   working_dir: '/usr/src/spring'
   command: mvn spring-boot:run
    
  react:
    container_name: react
    image: acrackintheice/expense-tracker-react
    ports:
      - "80:80"
    working_dir: '/usr/src/react'
    command: bash -c "npm start"

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: expensetracker2
      MYSQL_ROOT_PASSWORD: root
    ports:
     - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: