apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: expensetracker@expensetracker-1547098192339.iam.gserviceaccount.com
  name: expensetracker
  namespace: default