apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-dev.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: spring
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spring
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-dev.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: spring
    spec:
      containers:
      - args:
        - mvn
        - spring-boot:run
        image: maven
        imagePullPolicy: ""
        name: spring
        ports:
        - containerPort: 8080
        resources: {}
        workingDir: /usr/src/spring
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
