# Generated by Django 2.1.7 on 2019-04-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20190401_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='googleuser',
            name='googleId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
