# Dev Settings
spring:
    profiles: dev
    application:
        name: exp-tracker
    datasource:
        url: jdbc:mysql://private-db-mysql-sfo2-97936-do-user-7223154-0.a.db.ondigitalocean.com:25060/expensetracker?ssl-mode=REQUIRED
        username: doadmin
        password: dnsujrv4n1eydnka
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
--- # Prod Settings
spring:
    profiles: prod
    application:
        name: exp-tracker
    datasource:
        url: jdbc:mysql://db-mysql-sfo2-97936-do-user-7223154-0.a.db.ondigitalocean.com:25060/expense-tracker?ssl-mode=REQUIRED
        username: doadmin
        password: dnsujrv4n1eydnka
    jpa:
        hibernate:
            ddl-auto:  update
        show-sql: true