# Dev Settings
spring:
    profiles: dev
    application:
        name: exp-tracker
    datasource:
        url: jdbc:postgresql://postgres:5432/expensetracker
        username: expensetracker
        password: root
    jpa:
        show-sql: true
--- # Prod Settings
spring:
    profiles: prod
    application:
        name: exp-tracker
    datasource:
        url: jdbc:mysql://${DB_URL}/expensetracker?ssl-mode=REQUIRED
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        show-sql: true