# Dev Settings
spring:
    profiles: dev
    application:
        name: exp-tracker
    datasource:
        url: jdbc:postgresql://postgres:5432/expensetracker
        username: expensetracker
        password: root
        driverClassName: org.postgresql.Driver
    jpa:
        show-sql: true
--- # Prod Settings
spring:
    profiles: prod
    application:
        name: exp-tracker
    datasource:
        url: jdbc:${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driverClassName: org.postgresql.Driver
    jpa:
        show-sql: true