# Dev Settings
spring:
    profiles: dev
    application:
        name: exp-tracker
    datasource:
        url: jdbc:postgresql://postgres:5432/expensetracker
        username: expensetracker
        password: root
    jpa:
        show-sql: true
--- # Prod Settings
spring:
    profiles: prod
    application:
        name: exp-tracker
    datasource:
        url: jdbc:mysql://db-mysql-sfo2-97936-do-user-7223154-0.a.db.ondigitalocean.com:25060/expensetracker?ssl-mode=REQUIRED
        username: expensetracker
        password: dnsujrv4n1eydnka
    jpa:
        show-sql: true